# Generated by Django 3.0.5 on 2020-05-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200505_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=500, verbose_name='Content'),
        ),
    ]
